# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'venture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for venture
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'YelpAPI'
  pod 'BrightFutures'
  pod 'Alamofire'
  pod 'GooglePlaces'
  pod 'SwiftyJSON'

  target 'ventureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ventureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
